tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
template = "cog/changelog_template"
owner = "Gipphe"
repository = "SPT-MC-M60-Realism-Patch"
authors = [
  { signature = "Victor Nascimento Bakke", username = "Gipphe" }
]

[bump_profiles]

[packages]
